<?php

namespace app\admin\model;

use think\Model;

class Admin extends Model
{
    //
  /*y用户注册*/

  // 设置当前模型对应的完整数据表名称
  protected $table = 'lw_user';

  /*新增   包括修改*/
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }

  /*用户登录*/
  public function GetLogin(){

    $post_data = input('post.');

      if (is_array($post_data)){

        $ran = db('user')->where(['username'=>$post_data['user']])->field('id,username,password')->find();

        if ($ran) {

          if (md5($post_data['pass'] . config('code')) == $ran['password']) {
            $returnAjax['code'] = 1;
            $returnAjax['data'] = $ran['id'];
          } else {
            $returnAjax['code'] = -2;
          }
        }else{
          $returnAjax['code'] = -1;
        }

        return $returnAjax;
      }

  }



}
