<?php

namespace app\admin\model;

use think\Model;

class Login extends Model
{
  // 设置当前模型对应的完整数据表名称
  protected $table = 'bob_admin_user';

  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }


}
