<?php

/**
 * 首页导航
 */

namespace app\common\model;

use think\Model;

class AdminNavs extends Model
{
    // 添加或修改
    public function save($data = [], $where = [], $sequence = null)
    {
      return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
    }
}