<?php

namespace app\index\model;

use think\Model;

class Busrelease extends Model
{


    //
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }


  /*
   *  二级商家发布数据
   * */
  public function add()
  {
    $post_data = input('post.');
    try {
      $validate = new \think\Validate;
      $validate->rule([
        'company_pro|公司简介' => 'require|chsDash|max:300',
        'product_title|产品标题' => 'require|chsDash',
        'scope|经营范围' => 'require|chsDash',
        'corporate_name|公司名称' => 'require|chsDash|unique:busrelease',
        'credit_code|统一信用代码' => 'require|unique:busrelease',
        'reg_cap|注册资本' => 'require',
        'estab_date|成立日期' => 'require',
        'business_term|营业期限' => 'require',
        'legal_person|法人代表' => 'require|unique:busrelease',
        'reg_address|注册地址' => 'require',
        'pub_indu|发布行业' => 'require',
        'exh_region|展示地区' => 'require',
      ]);
      if ($validate->check($post_data)) {
          //执行添加
        $post_data['create_time'] = time();
        $post_data['user_id'] = session('?user_id')?session('user_id'):0;
        $res = $this->save($post_data);
        if ($res)
        jsonResponse(1, $this->id, '添加成功');
        else
          jsonResponse(-1, '','添加失败');

      } else {
        jsonResponse(-1, '', $validate->getError());
      }
    }catch (\Exception $e){
      jsonResponse(-1, '', $e->getMessage());

    }

  }
}
