<?php
/*转让信息+添加*/
namespace app\index\model;

use think\Model;

class Makeover extends Model
{
    //
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }


  public function add(){
    $post_data = input('post.');

    try{
      if ($post_data['town']>0 || $post_data['town']){
        $make_address = $post_data['province'].','.$post_data['city'].','.$post_data['town'];
      }elseif($post_data['city']>0 || $post_data['city']){
        $make_address = $post_data['province'].','.$post_data['city'];
      }else{
        jsonResponse(-1,'','请填写转让地址');
      }
      if ($post_data['town1']>0 || $post_data['town1']){
        $push_address = $post_data['province1'].','.$post_data['city1'].','.$post_data['town1'];
      }elseif($post_data['city1']>0 || $post_data['city1']){
        $push_address = $post_data['province1'].','.$post_data['city1'];
      }else{
        jsonResponse(-1,'','请填写推送地址');
      }
      if ($post_data['est_date_year'] && $post_data['est_date_m']){
        $est_date = $post_data['est_date_year'].'-'.$post_data['est_date_m'];
      }else{
        jsonResponse(-1,'','成立时间不能为空');
      }
      if (!array_key_exists('img',$post_data)){
        $img = '';
      }else{
        $img = implode(',',$post_data['img']);
      }

      $validate = new \think\Validate;
      $validate->rule([
        'title|标题' => 'require|chsDash|max:100',
        'cor_type|公司类别' => 'require|between:1,7',
        'cor_nature|公司性质' => 'require',
        'make_address_xq|转让地址详情' => 'require',
        'make_mode|转让方式' => 'require',
        'make_price|转让价格' => 'require|number',
        'reg_capital|注册资本' => 'require',
        'cor_scale|公司规模' => 'require',
        'scope|经营范围' => 'require',
        'contacts|联系人' => 'require',
        'phone|手机号' => 'require|/^[1]([3-9])[0-9]{9}$/',
        'push_indu|推送行业' => 'require',
        'push_time|推送时长' => 'require|between:1,6',
      ]);
      if ($validate->check($post_data)) {
        $post_data['make_address'] = $make_address;
        $post_data['push_address'] = $push_address;
        $post_data['est_date'] = $est_date;
        $post_data['user_id'] = session("?user_id")?session("user_id"):0;
        $post_data['create_time'] = time();
        $post_data['update_time'] = time();
        $post_data['status'] = 0;
        $post_data['photo'] = $img;
        $res = $this->allowField(true)->save($post_data);
        if ($res)
          jsonResponse(1,$this->id,'成功');
        else
          jsonResponse(-1,'','失败');
      } else {
        jsonResponse(-1, '', $validate->getError());
      }
    }catch (\Exception $e){
      return jsonResponse(-1,'',$e->getMessage());
    }
  }

}
