<?php

namespace app\index\model;

use think\Model;

class Meeting extends Model
{
    //
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }
}
