<?php

namespace app\index\model;

use think\Model;

class Member extends Model
{
    //
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }

  /*  个人会员认证  */
  public function add(){
    $post_data = input('post.');
    try{
      $validate = new \think\Validate;
      $validate->rule([
        'w_title|网站显示名字' => 'require|chsDash|max:100',
        'rel_name|真实姓名' => 'require',
        'idcard|身份证号' => 'require|max:18',
        'positive|身份证正面' => 'require',
        'other|身份证反面' => 'require',
        'province|省份' => 'require',
        'city|市级' => 'require|number',
        'town|区县' => 'require',
        'address|详细地址' => 'require',
        'indu|从事行业' => 'require',
        'phont|手机号' => 'require|/^[1]([3-9])[0-9]{9}$/',
      ]);
      if ($validate->check($post_data)) {
        $post_data['user_id'] = session("?user_id")?session("user_id"):0;
        $post_data['create_time'] = time();
        $post_data['update_time'] = time();
          $post_data['status'] = 0;
        $res = $this->allowField(true)->save($post_data);
        if ($res)
          jsonResponse(1,$this->id,'成功');
        else
          jsonResponse(-1,'','失败');
      } else {
        jsonResponse(-1, '', $validate->getError());
      }
    }catch (\Exception $e){
      return jsonResponse(-1,'',$e->getMessage());
    }
  }


  /*  企业会员认证  */
  public function entadd(){
    $post_data = input('post.');
    try{
      $validate = new \think\Validate;
      $validate->rule([
        'w_title|公司名称' => 'require|chsDash|max:100',
        'idcard|统一社会信用代码' => 'require|max:30',
        'logo|营业执照' => 'require',
        'province|省份' => 'require',
        'city|市级' => 'require|number',
        'town|区县' => 'require',
        'address|详细地址' => 'require',
        'phont|固定电话' => 'require',
      ]);
      if ($validate->check($post_data)) {
        $post_data['user_id'] = session("?user_id")?session("user_id"):0;
        $post_data['create_time'] = time();
        $post_data['update_time'] = time();
        $post_data['type'] = 2;
        $res = $this->allowField(true)->save($post_data);
        if ($res)
          jsonResponse(1,$this->id,'成功');
        else
          jsonResponse(-1,'','失败');
      } else {
        jsonResponse(-1, '', $validate->getError());
      }
    }catch (\Exception $e){
      return jsonResponse(-1,'',$e->getMessage());
    }
  }

}
