<?php

namespace app\index\model;

use think\Model;

class Recruit extends Model
{
    //
  public function save($data = [], $where = [], $sequence = null)
  {
    return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
  }

  public function add(){
    $post_data = input('post.');
    try{
      $validate = new \think\Validate;
      $validate->rule([
        'title|标题' => 'require|max:100',
        'pos_name|职位名称' => 'require',
        'work_na|工作性质' => 'require',
        'number_peo|招聘人数' => 'require|number',
        'salary|月薪范围' => 'require|number',
        'work_addr_p|工作地址' => 'require',
        'work_addr_c|工作地址' => 'require',
        'work_addr_t|工作地址' => 'require',
        'work_addr_xq|工作地址详情' => 'require',
        'brief|职位介绍' => 'require',
        'contacts|联系人' => 'require',
        'phone|手机号' => 'require|/^[1]([3-9])[0-9]{9}$/',
        'push_indu|推送行业' => 'require',
        'push_addr_p|推送地区' => 'require',
        'push_addr_t|推送地区' => 'require',
        'push_addr_c|推送地区' => 'require',
        'push_time|推送时长' => 'require|between:1,6',

      ]);
      if ($validate->check($post_data)) {
        $post_data['user_id'] = session("?user_id")?session("user_id"):1;
        $post_data['create_time'] = time();
        $post_data['update_time'] = time();
        $post_data['bright'] = implode(',',array_filter($post_data['bright']));
        $res = $this->allowField(true)->save($post_data);
        if ($res)
          jsonResponse(1,$this->id,'成功');
        else
          jsonResponse(-1,'','失败');
      } else {
        jsonResponse(-1, '', $validate->getError());
      }
    }catch (\Exception $e){
      return jsonResponse(-1,'',$e->getMessage());
    }
  }
}
